using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Consumer.MongoDbEntity
{
    public abstract class ConsumerLogBase<T>
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // external ID or key, which may be easier to reference (ex: 1,2,3 etc.)
        public Guid EventId { get; set; }

        public DateTime EventUtcTime { get; set; }

        public T Id { get; set; }

        public DateTime CreateTime { get; set; }
    }
}
